"""add_fabricant

Revision ID: 24c75ae5e299
Revises: 47ce4fc5b947
Create Date: 2026-04-20 14:28:02.146921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c75ae5e299'
down_revision: Union[str, Sequence[str], None] = '47ce4fc5b947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cellules', sa.Column('fabricant', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cellules', 'fabricant')
    # ### end Alembic commands ###
