"""add_phase1_fields

Revision ID: 47ce4fc5b947
Revises: 
Create Date: 2026-04-20 14:19:45.571277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ce4fc5b947'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cellules', sa.Column('chimie', sa.String(length=20), nullable=True))
    op.add_column('cellules', sa.Column('cycle_life', sa.Integer(), nullable=True))
    op.add_column('cellules', sa.Column('dod_reference_pct', sa.Float(), nullable=True))
    op.add_column('cellules', sa.Column('c_rate_max_discharge', sa.Float(), nullable=True))
    op.add_column('cellules', sa.Column('c_rate_max_charge', sa.Float(), nullable=True))
    op.add_column('cellules', sa.Column('energie_volumique_wh_l', sa.Float(), nullable=True))
    op.add_column('cellules', sa.Column('eol_capacity_pct', sa.Float(), nullable=True))
    op.add_column('cellules', sa.Column('energie_massique_wh_kg', sa.Float(), nullable=True))
    op.add_column('cellules', sa.Column('cutoff_voltage_v', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cellules', 'cutoff_voltage_v')
    op.drop_column('cellules', 'energie_massique_wh_kg')
    op.drop_column('cellules', 'eol_capacity_pct')
    op.drop_column('cellules', 'energie_volumique_wh_l')
    op.drop_column('cellules', 'c_rate_max_charge')
    op.drop_column('cellules', 'c_rate_max_discharge')
    op.drop_column('cellules', 'dod_reference_pct')
    op.drop_column('cellules', 'cycle_life')
    op.drop_column('cellules', 'chimie')
    # ### end Alembic commands ###
